# Prettier preserves hard line breaks in prose, humans should be able to wrap by linguistic units like clauses.
MD013:
  line_length: 160
  code_block_line_length: 120
MD046: { style: fenced }

# These rules are covered by prettier and could potentially lead to conflicts
MD003: false
MD004: false
MD005: false
MD006: false
MD007: false
MD009: false
MD010: false
MD012: false
MD019: false
MD022: false
MD023: false
MD027: false
MD029: false
MD030: false
MD031: false
MD032: false
MD035: false
MD047: false
MD048: false
