DISABLE:
  - COPYPASTE
  - GROOVY
  - KOTLIN
  - PROTOBUF
  - SPELL
  - SQL
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_REMARK_LINT
  - YAML_PRETTIER
APPLY_FIXES:
  - JSON_PRETTIER
DEFAULT_BRANCH: main
ADDITIONAL_EXCLUDED_DIRECTORIES: [themes]
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
JSON_PRETTIER_FILE_EXTENSIONS: ['*']
JSON_PRETTIER_CONFIG_FILE: LINTER_DEFAULT
JSON_PRETTIER_ARGUMENTS: '-u'
JSON_V8R_DISABLE_ERRORS: true
MARKDOWN_MARKDOWNLINT_FILE_EXTENSIONS: ['.md', '.Rmd', '.Rmarkdown']
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: LINTER_DEFAULT
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
YAML_V8R_DISABLE_ERRORS: true
YAML_YAMLLINT_CONFIG_FILE: LINTER_DEFAULT
