theme: "hugo-geekdoc"
baseURL: https://gin-tonic.netlify.app/
languageCode: en-us
title: Tonic Template

markup:
  goldmark:
    renderer:
      unsafe: true

ignoreFiles:
  - "\\.Rmd$"
  - "\\.Rmarkdown$"
  - "_cache$"
  - "\\.knit\\.md$"
  - "\\.utf8\\.md$"
