baseURL: https://gin-tonic.netlify.app/
languageCode: en-US

theme: 'hugo-theme-learn'
title: Tonic project documentation

ignoreFiles:
  - "\\.Rmd$"
  - "\\.Rmarkdown$"
  - '_cache$'
  - "\\.knit\\.md$"
  - "\\.utf8\\.md$"
  - "\\.bib$"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  editURL: https://github.com/tonic-team/tonic.site/edit/main/content/
  disableNextPrev: false
  disableSearch: true
  disableMermaid: true
